apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
  namespace: penguin-protein
type: Opaque
stringData:
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "TYNLXp7P6Il0PG7ZJebiC7GUX-rBojBUcg5NGH7yJE8"
